name: Deployment CI

on:
  push:
    branches:
      - "master"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build:single-spa:y-fe-parcel-comments

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/y-fe-parcel-comments:latest
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
